name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的 Fork 仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 配置 GitHub 身份验证
        run: |
          git config --global credential.helper 'store'
          echo "https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: 添加上游仓库，与保留本地.github/workflows/ 目录内容不更新
        run: |
          git remote add upstream https://github.com/cmliu/CF-Workers-docker.io || true # 这里改为你的上游仓库
          git fetch upstream
          git checkout master  # 这里改为你的上游主要分支，一般可能是main或者master
          git checkout -b temp-merge  # 创建一个临时分支
          git merge -X theirs upstream/master --allow-unrelated-histories  # 默认保留上游代码
          git checkout master  # 回到主分支
          rsync -a .github/workflows/ ../workflows-backup/  # 备份工作流目录
          git reset --hard temp-merge  # 硬重置到合并后的状态
          rsync -a ../workflows-backup/ .github/workflows/  # 恢复工作流目录
          rm -rf ../workflows-backup  # 删除临时备份
          git add .github/workflows/
          git commit -m "同步上游代码，并保留本地 workflows" || true
          git branch -D temp-merge  # 删除临时分支

      - name: 推送到 Fork 仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master --force --no-verify  # 这里改为你的上游主要分支，一般可能是main或者master
