name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的 Fork 仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 配置 GitHub 身份验证
        run: |
          git config --global credential.helper 'store'
          echo "https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: 添加上游仓库，并保留本地 .github/workflows/ 目录
        run: |
          git remote add upstream https://github.com/cmliu/CF-Workers-docker.io || true
          git fetch upstream
          git checkout main
          git checkout -b temp-merge
          
          # 先合并上游，但跳过 .github/workflows 目录
          git read-tree --prefix=.github/workflows/ -u HEAD  # 备份本地 workflows
          git merge -X theirs upstream/main --allow-unrelated-histories || true
          git checkout HEAD -- .github/workflows/  # 恢复本地 workflows
          
          git checkout main
          git reset --hard temp-merge  # 硬重置到合并后的状态
          git branch -D temp-merge
          
          git add .github/workflows/
          git commit -m "同步上游代码，并保留本地 workflows" || true

      - name: 推送到 Fork 仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --force --no-verify  # 这里改为你的上游主要分支，一般可能是main或者master
